# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install Dependencies
      run: npm install
      
    - name: react-family
      run: npm run build  
       
    - name: Stop pm2
      run: pm2 stop nodedeploy
      if: ${{failure()}}
    
    - name: Start pm2
      run: pm2 start backend/index.js --name nodeploy

